services:
  - type: web
    name: edusphere
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /up
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        fromService:
          type: web
          name: edusphere
          property: host
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: edusphere-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: SEED_DEMO
        value: "true"

databases:
  - name: edusphere-db
    plan: free
