server {
    listen 80;
    server_name _;
    root /var/www/public;
    index index.html index.php;

    client_max_body_size 32M;

    location = / {
        try_files /vitrine/index.html =404;
    }

    location = /index.html {
        try_files /vitrine/index.html =404;
    }

    location = /connexion.html {
        try_files /vitrine/connexion.html =404;
    }

    location = /404.html {
        try_files /vitrine/404.html =404;
    }

    location = /favicon.ico {
        try_files /favicon.ico /vitrine/favicon.ico =404;
    }

    location /assets/ {
        try_files /vitrine$uri =404;
    }

    location = /manifest.json {
        try_files /vitrine/manifest.json =404;
    }

    location = /production-url {
        try_files /vitrine/production-url =404;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
